---
title: "Day 5 - Applications"
#author: "Jonathan Phillips"
#date: "May 13, 2017"
output: html_document
---

<style>
.column-left{
  float: left;
  width: 50%;
  text-align: left;
}
.column-right{
  float: right;
  width: 50%;
  text-align: right;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(knitr)
```

**Morning**

1. [Lecture](https://jonnyphillips.github.io/Intro_Spatial/Day_5/Slides_Day_5_v4.html)
3. [Demonstration of using QGIS and Geoda for Political Science Applications](https://docs.google.com/presentation/d/1v41kgi4Z45Eo1yx_lwXE-VCzSa_k19acMSCJZGaIdg4/preesnt?usp=sharing)
4. [Demonstration of using R for Political Science Applications](https://docs.google.com/presentation/d/1EPO6gaLVg0nNedrOavrZ__ioSCQes98DKLPVN1VudQc/present?usp=sharing)

**Afternoon**

Your task in the lab sessions is to produce **TWO** outputs answering the same questions:

a. From your analysis in QGIS, a Word document containing the answers to the questions below, including any maps pasted as images.
b. From your analysis in R, A HTML document produced directly from your analysis.

Lab Questions: 

1. [QGIS] Which Brazilian state is the most compact according to the Polsby-Popper Test? Which is the least compact?
2. [GEODA] What is the Bivariate Moran's I between Voting (Pct_Votes) and Income (PIB_PER) in Brazilian municipalities?
3. [R] Is the population density higher on the Brazil side of the international border with other Latin American countries?

Files:

[Brazilian states](https://jonnyphillips.github.io/Intro_Spatial/Day_5/Data/Brazil_states.zip)  
[Brazilian Municipality Income and Voting](https://jonnyphillips.github.io/Intro_Spatial/Day_5/Data/Br_muns_votes.zip)

[South America Population Density 2000](https://jonnyphillips.github.io/Intro_Spatial/Day_5/Data/lacpopd00.tif/lacpopd00.zip)  
[Brazil Border Inland](https://jonnyphillips.github.io/Intro_Spatial/Day_5/Data/Br_Border_interior.zip)

