---
title: "Day 3 - Raster Data"
#author: "Jonathan Phillips"
#date: "May 13, 2017"
output: html_document
---

<style>
.column-left{
  float: left;
  width: 50%;
  text-align: left;
}
.column-right{
  float: right;
  width: 50%;
  text-align: right;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(knitr)
```

**Morning**

1. [Lecture](https://jonnyphillips.github.io/Intro_Spatial/Day_3/Slides_Day_3_v5.html)
3. [Demonstration of using QGIS for Raster Data](https://docs.google.com/presentation/d/1GJDfwgi__l14cC4_tpjKy_J24uhAaYtq1z5fAQHsZV0/present#slide=id.g4c7ab4222d_0_368)
4. [Demonstration of using R for Raster Data](https://docs.google.com/presentation/d/1xF05gvjxshdqjPxd7vcnGIcP7SNcf-3EPsk7j9unpgM/present#slide=id.g4c790dbd3d_0_5)

**Afternoon**

Your task in the lab sessions is to produce **TWO** outputs answering the same questions:

a. From your analysis in QGIS, a Word document containing the answers to the questions below, including any maps pasted as images.
b. From your analysis in R, A HTML document produced directly from your analysis.

Lab Questions: 

1. Produce two new raster files of population density that are limited to only Brazil's territory (one for 1960, one for 2000).   
1. Produce a new map of how the distribution of Brazil’s population has changed over the last 50 years.  
2. Which municipalities have seen the greatest increases in mean population density between 1960 and 2000?   
  
Files:
[Population Density 2000](https://jonnyphillips.github.io/Intro_Spatial/Day_3/Data/lacpopd00.tif/lacpopd00.zip)  
[Population Density 1960](https://jonnyphillips.github.io/Intro_Spatial/Day_3/Data/lacpopd60.tif/lacpopd60.zip)  
[Brazil Outline](https://jonnyphillips.github.io/Intro_Spatial/Day_3/Data/Br_Outline.zip)  
[Brazilian Municipalities](https://jonnyphillips.github.io/Intro_Spatial/Day_3/Data/municipalities.zip)   
