---
title: "Day 4 - Measurement"
#author: "Jonathan Phillips"
#date: "May 13, 2017"
output: html_document
---

<style>
.column-left{
  float: left;
  width: 50%;
  text-align: left;
}
.column-right{
  float: right;
  width: 50%;
  text-align: right;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(knitr)
```

**Morning**

1. [Lecture](https://jonnyphillips.github.io/Intro_Spatial/Day_4/Slides_Day_4_v5.html)
3. [Demonstration of using QGIS and Geoda for Measurement](https://docs.google.com/presentation/d/1ZxPQku1ysGnewShK1cmWceRqFlK36RJFVSug90Dpup0/present?usp=sharing)
4. [Demonstration of using R for Measurement](https://docs.google.com/presentation/d/1x4XAE7V80rTmqOpvZL9Asf38yV5gx5FEqQ1w8UN8yXs/present?usp=sharing)

**Afternoon**

Your task in the lab sessions is to produce **TWO** outputs answering the same questions:

a. From your analysis in Geoda and QGIS, a Word document containing the answers to the questions below, including any maps pasted as images.
b. From your analysis in R, A HTML document produced directly from your analysis.

Lab Question: 

1. [QGIS] Join the Brazilian municipalities shapefile with the inequality (Theil) CSV data. Save this new layer as a new shapefile. 
2. [GeoDa+R] Using the shapefile from part (1), compare one contiguity-based and one distance-based spatial weights matrix for Brazilian municipalities.
3. [GeoDa+R] Calculate the Moran's I measure of spatial autocorrelation for the Theil measure of inequality in Brazilian municipalities. How do you interpret this number?
4. [GeoDa+R] Produce a map of clusters of Local Indicators of Spatial Autocorrelation (LISA). Where is inequality clustered in Brazil? Where are the places of surprising low inequality?
5. [R] How racially segregated is Roraima state based on the census data?

Files:
[Brazilian Municipalities Shapefile](https://jonnyphillips.github.io/Intro_Spatial/Day_4/Data/municipalities.zip)  
[Inequality Data for Brazilian Municipalities](https://jonnyphillips.github.io/Intro_Spatial/Day_4/Data/ineq_mun.csv)  
[Moran's I Functions](https://jonnyphillips.github.io/Intro_Spatial/Day_4/Functions.R)

[Census data for Roraima State](https://jonnyphillips.github.io/Intro_Spatial/Day_4/Data/Roraima_race.zip)
